# Dataset config
name: "plant-tech-raw-v1"
bucket_path_prefix: {path}
max_samples: 50
metadata_config:
  raw_labels:
    source: bq-query
    query: {bq-query}
    key: {key}
    value: {value}
    label_map:
      "label_key_1": label_name_1
      "label_key_2": label_name_2